### PR TITLE
Fix 3rd party dependency

### PR DESCRIPTION
**Pull request by baranovoleg**

### CODE REVIEW

**Comment by baranovoleg** [comment]
> go mod why launchpad.net/gocheck
> %MY_LOCAL_MODULE_NAME%
> github.com/hashicorp/consul/watch
> github.com/hashicorp/consul/watch.test
> github.com/hashicorp/consul/agent
> github.com/hashicorp/go-discover
> github.com/hashicorp/go-discover/provider/digitalocean
> github.com/digitalocean/godo
> github.com/tent/http-link-go
> github.com/tent/http-link-go.test
> launchpad.net/gocheck

But on the https://launchpad.net/gocheck says PROJECT MOVED: https://github.com/go-check/check

**Comment by baranovoleg** [comment]
PING!

**Comment by azr** [comment]
Hello there, this PR is also interesting for me mainly for the same reasons:

> go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir https://launchpad.net/~niemeyer/gocheck/trunk . in /Users/travis/gopath/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exec: "bzr": executable file not found in $PATH

**Comment by azr** [comment]
Actually tent doesn't exist anymore it seems: https://tent.io/

**Comment by azr** [comment]
this should be fixed by https://github.com/digitalocean/godo/pull/223

**Comment by azr** [comment]
or just running `GO111MODULE=on go get github.com/digitalocean/godo` solved it for me :D

**Comment by baranovoleg** [comment]
Yep, fixed by 
https://github.com/digitalocean/godo/commit/0168bd6520364c819c8462137e72412a1ff2b447

**Pull request closed without merging**
